server:
  port: 5000

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: USER
              uri: "lb://USER"
              predicates:
                - Path= /auth/**, /api/admin/users/**, users/**

            - id: SALON
              uri: "lb://SALON"
              predicates:
                - Path= /salons/**, /api/salons/**, /api/admin/salons/**

            - id: CATEGORY
              uri: "lb://CATEGORY"
              predicates:
                - Path= /api/categories/**


            - id: SERVICE-OFFERING
              uri: "lb://SERVICE-OFFERING"
              predicates:
                - Path= /api/service-offering/**

            - id: BOOKING
              uri: "lb://BOOKING"
              predicates:
                - Path= /api/bookings/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka/
