services:

  userdb:
    image: mysql
    container_name: userdb
    ports:
      - "3301:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    networks:
      - aliusa01

  salondb:
    image: mysql
    container_name: salondb
    ports:
      - "3302:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: salondb
    networks:
      - aliusa01

  bookingdb:
    image: mysql
    container_name: bookingdb
    ports:
      - "3303:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookingdb
    networks:
      - aliusa01

  categorydb:
    image: mysql
    container_name: categorydb
    ports:
      - "3304:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: categorydb
    networks:
      - aliusa01

  service-offeringdb:
    image: mysql
    container_name: service-offeringdb
    ports:
      - 3309:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service-offeringdb
    networks:
      - aliusa01



  eurekaserver:
    image: "aliusa01/eureka-server-yt:v1"
    ports:
      - "8070:8070"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: eurekaserver
    #        environment:
    #          SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
    #        depends_on:
    #          configserver:
    #            condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - aliusa01


  user:
    image: "aliusa01/salon-user-yt:v1"
    ports:
      - "5001:5001"
    container_name: user
    healthcheck:
      test: "curl --fail --silent user:5001/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      #      configserver:
      #        condition: service_healthy
      userdb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_APPLICATION_NAME: "user"
      SPRING_PROFILES_ACTIVE: default
      #      SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8071/"
      SPRING_DATASOURCE_URL: "jdbc:mysql://userdb:3306/userdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - aliusa01

  salon:
    image: "aliusa01/salon-yt:v1"
    ports:
      - "5002:5002"
    container_name: salon
    healthcheck:
      test: "curl --fail --silent localhost:5002/actuator/health/readiness | grep UP || exit 1"
 
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      salondb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_APPLICATION_NAME: "salon"
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: "jdbc:mysql://salondb:3306/salondb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - aliusa01

  booking:
    image: "aliusa01/booking-yt:v1"
    ports:
      - "5003:5003"
    container_name: booking
    healthcheck:
      test: "curl --fail --silent booking:5003/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      #      configserver:
      #        condition: service_healthy
      bookingdb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_APPLICATION_NAME: "booking"
      SPRING_PROFILES_ACTIVE: default
      #      SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8071/"
      SPRING_DATASOURCE_URL: "jdbc:mysql://bookingdb:3306/bookingdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - aliusa01

  category:
    image: "aliusa01/category-yt:v1"
    ports:
      - "5004:5004"
    container_name: category
    healthcheck:
      test: "curl --fail --silent category:5004/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      #      configserver:
      #        condition: service_healthy
      categorydb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_APPLICATION_NAME: "category"
      SPRING_PROFILES_ACTIVE: default
      #      SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8071/"
      SPRING_DATASOURCE_URL: "jdbc:mysql://categorydb:3306/categorydb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - aliusa01

  service-offering:
    image: "aliusa01/service-offering-yt:v1"
    ports:
      - "5008:5008"
    container_name: service-offering
    healthcheck:
      test: "curl --fail --silent service-offering:5008/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      #      configserver:
      #        condition: service_healthy
      service-offeringdb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_APPLICATION_NAME: "service-offering"
      SPRING_PROFILES_ACTIVE: default
      #      SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8071/"
      SPRING_DATASOURCE_URL: "jdbc:mysql://service-offeringdb:3306/service-offeringdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - aliusa01



  gatewayserver:
    image: "aliusa01/gateway-server-yt:v1"
    ports:
      - "5000:5000"
    container_name: gatewayserver
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    #    depends_on:
    #      configserver:
    #        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - aliusa01

networks:
  aliusa01:
    driver: "bridge"







