server:
  port: 5007

spring:
  application:
    name: salon_notifications


  datasource:
    url: jdbc:mysql://localhost:3306/salon_notificationdb?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
